FROM docker as docker
FROM node as node

FROM jenkins/jnlp-slave:latest
USER root
COPY --from=docker /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/bin/ /usr/local/bin/
COPY --from=node /usr/local/lib/node_modules/npm/ /usr/local/lib/node_modules/npm/
COPY --from=node /opt/yarn-v1.10.1/ /opt/yarn-v1.10.1/

# RUN apt-get update
# RUN apt-get -y install apt-transport-https \
#         ca-certificates \
#         curl \
#         gnupg2 \
#         software-properties-common 
# RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
#     add-apt-repository \
#         "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
#         $(lsb_release -cs) \
#         stable"
# RUN apt-get update
# RUN apt-get install -y docker-ce
# RUN apt-get install -y curl \
#     && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
#     && apt-get install -y nodejs \
#     && curl -L https://www.npmjs.com/install.sh | sh
# RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
# RUN apt-get install -y yarn

#RUN usermod -aG docker jenkins
#USER jenkins